version: '3'

volumes:
  foodgram_data_production:
  static_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data_production:/var/lib/postgresql/data
  backend:
    image: vladrnd/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: vladrnd/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: vladrnd/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
