version: '3'

volumes:
  pg_data:
  static:
  media:
  docs:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vladrnd/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    env_file: .env
    image: vladrnd/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vladrnd/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/app/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
