# Generated by Django 5.0.4 on 2024-04-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alone_app', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
    ]
